### ISSUE TITLE
"TypeError: __call__() takes 1 positional argument but 2 were given"  when running brain_trader.py

### ISSUE THREAD

**Issue by canercak** [nickwilliamsnewby/cryptochronolonic#2]
Hi,
First of all I want to thank you for open sourcing this project. I want to contribute to it if I can. 
I can only trade on binance so I tried to make binance branch work. Installed pureples and  neat as you explained but I got the below error when I tried to run brain_trader.py. Note that I'm running the PaperTrader and Didn't change any settings. 

```
BTC_LPT written
BTC_GRIN written
Traceback (most recent call last):
  File "brain_trader.py", line 342, in <module>
    PaperTrader(7200, 1.0, 89)
  File "brain_trader.py", line 240, in __init__
    self.poloTrader()
  File "brain_trader.py", line 302, in poloTrader
    net = network.create_phenotype_network_nd('paper.png')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pureples-0.0-py3.6.egg/pureples/es_hyperneat/es_hyperneat_torch.py", line 62, in create_phenotype_network_nd
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pureples-0.0-py3.6.egg/pureples/es_hyperneat/es_hyperneat_torch.py", line 276, in es_hyperneat_nd
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pureples-0.0-py3.6.egg/pureples/es_hyperneat/es_hyperneat_torch.py", line 176, in division_initialization_nd
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pureples-0.0-py3.6.egg/pureples/hyperneat/hyperneat.py", line 122, in query_torch_cppn
TypeError: __call__() takes 1 positional argument but 2 were given

```
it gives that out in here.."create_phenotype_"

```
   def poloTrader(self):
        end_prices = {}
        active = self.get_one_bar_input_2d()
        self.load_net()
        sub = Substrate(self.in_shapes, self.out_shapes)
        network = ESNetwork(sub, self.cppn, self.params)
        net = network.create_phenotype_network_nd('test.png')
        net.reset() 
```

Tried uninstalling/installing pureples and also tried with master and  torchv branch you created but I still get the same error. Also tried just running create_phenotype_network() but it gives out "too many values to unpack (expected 2)" error.
Do you have any idea why this happens?

By the way, how do you backtest the data?. As far as I see after training you run papertrader or livetrade, could not see anything for backtesting so far..is there is something I am missing?
thank you for your help.

**Comment by ai-nick** [comment]
hey sorry for taking so long to get back, but i will add some things into the read me that address backtesting/validation and also the error you encountered when i merge my current branch back into master, new-latest is the most recent branch and i plan on removing pytorch-neat support as it actually isnt any faster than the rnn's provided in neat-python (not using backprop or sgd at all so gpu optimizations are kinda a wash compared to the hassle of install py torch)

**Comment by ai-nick** [comment]
hey been super busy but havent forgot about this will be revisiting over the weekend!
